---
# tasks file for docker_installer

- name: CentOS Docker installation
  import_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: Ubuntu Docker installation
  import_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

